# Generated by Django 5.1.15 on 2026-09-06 10:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('selling_type', models.CharField(choices=[('UNIT', 'Unit / Packaged'), ('KG', 'Kilogram (Weight / Loose)')], default='UNIT', help_text='UNIT for packaged goods, KG for loose goods by weight.', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Wholesale / cost price per unit or per KG.', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Retail selling price per unit or per KG.', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stock level. Stores integers for UNIT or 3-decimal values for KG.', max_digits=12)),
                ('feature_vector', models.JSONField(blank=True, help_text='Visual embedding vector (L2-normalized float list) generated from product image.', null=True)),
                ('is_loose', models.BooleanField(db_index=True, default=False, help_text='True for unbranded/loose commodities (e.g., plain bags of sugar, rice, flour).')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The shopkeeper who owns this inventory record.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'shopgenie_products',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_product_per_shopkeeper')],
            },
        ),
    ]
